# -*- coding: utf-8 -*-
"""Hiral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Y2WFjnYuRm81ybAKYl2zf8PHDmS7Cbq
"""

import pandas as pd

df = pd.read_csv("/content/Cigarette Consumption(in).csv")
df.head()

import json
import urllib.request

# Load USA states GeoJSON
url = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
with urllib.request.urlopen(url) as response:
    states_geo = json.loads(response.read())





!pip install jupyter-dash==0.4.2 dash==2.11.1

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output
import json, urllib.request

# --------------------------
# Load dataset
# --------------------------
df = pd.read_csv("/content/Cigarette Consumption(in).csv")
df["state"] = df["state"].str.upper()

years = sorted(df["Year"].unique())
states = sorted(df["state"].unique())

# Region mapping for sunburst
region_map = {
    "WA":"West","OR":"West","CA":"West","NV":"West","ID":"West","MT":"West",
    "WY":"West","UT":"West","CO":"West","AZ":"West","NM":"West","AK":"West","HI":"West",
    "ND":"Midwest","SD":"Midwest","NE":"Midwest","KS":"Midwest","MN":"Midwest",
    "IA":"Midwest","MO":"Midwest","WI":"Midwest","IL":"Midwest","IN":"Midwest","MI":"Midwest","OH":"Midwest",
    "OK":"South","TX":"South","AR":"South","LA":"South","KY":"South","TN":"South",
    "MS":"South","AL":"South","GA":"South","FL":"South","SC":"South","NC":"South",
    "VA":"South","WV":"South","MD":"South","DE":"South",
    "PA":"Northeast","NY":"Northeast","NJ":"Northeast","CT":"Northeast","RI":"Northeast",
    "MA":"Northeast","VT":"Northeast","NH":"Northeast","ME":"Northeast",
    "DC":"Northeast"
}
df["Region"] = df["state"].map(region_map).fillna("Other")

# USA GeoJSON
url = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
with urllib.request.urlopen(url) as response:
    states_geo = json.loads(response.read())

# --------------------------
# Dash App
# --------------------------
app = Dash(__name__)

app.layout = html.Div([
    html.Div([
        html.Div("Worldwide", className="tab active-tab"),
        html.Div("Country", className="tab"),
        html.Div("Data", className="tab"),
    ], className="top-bar"),

    html.H2("Daily smoking patterns (US States)", style={"text-align":"center"}),

    html.Div([
        html.Div([
            dcc.Graph(id="usa_map", style={"height":"420px"}),
            html.Div(id="caption", style={"text-align":"center","font-size":"12px"})
        ], style={"width":"60%", "display":"inline-block"}),

        html.Div([
            dcc.Graph(id="sunburst_chart", style={"height":"420px"})
        ], style={"width":"38%", "display":"inline-block","margin-left":"2%"})
    ]),

    html.Div([
        dcc.Graph(id="timeseries_all", style={"height":"260px"})
    ], style={"width":"96%", "margin":"0 auto"}),

    html.Div([
        html.Span("Year:", style={"margin-right":"5px"}),
        dcc.Slider(
            id="year_slider",
            min=min(years),
            max=max(years),
            step=None,
            value=max(years),
            marks={int(y): str(int(y)) for y in years[::5]}
        )
    ], className="bottom-controls")
])

# --------------------------
# Callbacks
# --------------------------
@app.callback(
    Output("usa_map", "figure"),
    Output("caption", "children"),
    Input("year_slider", "value")
)
def update_map(year):
    dff = df[df["Year"] == year]

    fig = px.choropleth(
        dff,
        locations="state",
        locationmode="USA-states",
        color="Y",
        scope="usa",
        color_continuous_scale="YlOrRd",
        labels={"Y":"Cigarette Consumption"}
    )

    fig.update_layout(
        margin=dict(l=0,r=0,t=0,b=60),
        coloraxis_colorbar=dict(
            orientation="h",
            y=-0.25,
            x=0.5,
            xanchor="center",
            title=""
        )
    )
    return fig, f"Cigarette consumption in {year}"

@app.callback(
    Output("sunburst_chart", "figure"),
    Input("year_slider", "value")
)
def update_sunburst(year):
    dff = df[df["Year"] == year]
    sun = dff.groupby(["Region","state"], as_index=False)["Y"].mean()

    fig = px.sunburst(
        sun,
        path=["Region","state"],
        values="Y",
        title=f"Consumption by region/state ({year})"
    )
    fig.update_layout(margin=dict(l=0,r=0,t=40,b=0))
    return fig

@app.callback(
    Output("timeseries_all", "figure"),
    Input("year_slider", "value")
)
def update_timeseries(year):
    fig = go.Figure()

    for st in states:
        temp = df[df["state"] == st]
        fig.add_trace(go.Scatter(
            x=temp["Year"],
            y=temp["Y"],
            mode="lines",
            line=dict(width=1, color="rgba(70,80,200,0.12)"),
            hoverinfo="skip",
            showlegend=False
        ))

    avg = df.groupby("Year", as_index=False)["Y"].mean()
    fig.add_trace(go.Scatter(
        x=avg["Year"],
        y=avg["Y"],
        mode="lines",
        line=dict(width=3, color="rgba(0,0,100,0.9)"),
        name="US Mean"
    ))

    fig.update_layout(
        title="Cigarette consumption over time",
        xaxis_title="Year",
        yaxis_title="Y",
        margin=dict(l=40,r=20,t=40,b=40)
    )

    return fig

# --------------------------
# Custom CSS
# --------------------------
app.index_string = """
<!DOCTYPE html>
<html>
<head>
    {%metas%}
    <title>Tobacco Viz Clone</title>
    {%favicon%}
    {%css%}
    <style>
    body { font-family: "Helvetica Neue", Arial; margin:0; }
    .top-bar { background:#b6e57c; padding:6px 20px; display:flex; }
    .tab { padding:6px 18px; margin-right:6px; background:#d9f2b4; }
    .active-tab { background:black; color:white; }
    .bottom-controls { background:#f5f5f5; padding:10px 20px; }
    </style>
</head>
<body>
    {%app_entry%}
    <footer>
        {%config%}
        {%scripts%}
        {%renderer%}
    </footer>
</body>
</html>
"""

# --------------------------
# Run server (port 8060)
# --------------------------
app.run_server(host="0.0.0.0", port=8060)

# ============================================================
# DASHBOARD B — NATIONAL TREND (LOESS + Policy Events)
# Port: 8061
# ============================================================

import numpy as np
from statsmodels.nonparametric.smoothers_lowess import lowess
import ruptures as rpt

# ---- LOESS Function ----
def loess_smooth(x, y, frac=0.25):
    sm = lowess(y, x, frac=frac)
    return sm[:,0], sm[:,1]

# ---- Changepoint Detection (COLAB-COMPATIBLE) ----
def detect_cp(series, n_bkps=3):
    algo = rpt.Binseg(model="rbf").fit(series)
    result = algo.predict(n_bkps=n_bkps)
    return result[:-1]

# ---- Prepare national data ----
national = df.groupby("Year", as_index=False)["Y"].mean()
years = national["Year"].values
values = national["Y"].values
cp_idx = detect_cp(values, n_bkps=3)

# ---- DASH APP ----
from dash import Dash, dcc, html, Input, Output
import plotly.graph_objects as go

app2 = Dash(__name__)

app2.layout = html.Div([
    html.H2("National Smoking Trend (1990–2019): LOESS + Policy Events",
            style={"text-align": "center"}),

    dcc.Graph(id="loess_plot"),

    html.Div("Adjust LOESS Smoothness:",
             style={"margin-top":"20px","font-weight":"bold"}),

    dcc.Slider(
        id="smooth_slider2",
        min=0.1, max=0.6, step=0.05,
        value=0.25,
        marks={0.1:"0.1", 0.3:"0.3", 0.5:"0.5"}
    )
])

@app2.callback(
    Output("loess_plot", "figure"),
    Input("smooth_slider2", "value")
)
def update_loess(smooth):
    x_s, y_s = loess_smooth(national["Year"], national["Y"], frac=smooth)

    fig = go.Figure()

    # Raw data
    fig.add_trace(go.Scatter(
        x=national["Year"],
        y=national["Y"],
        mode="markers+lines",
        name="Actual",
        marker=dict(size=6, color="#6daffe"),
        line=dict(width=2)
    ))

    # LOESS
    fig.add_trace(go.Scatter(
        x=x_s, y=y_s,
        mode="lines",
        name="LOESS Trend",
        line=dict(color="#0047ab", width=4)
    ))

    # Policy Lines
    fig.add_vline(x=1998, line_width=2, line_dash="dash", line_color="red",
                  annotation_text="1998 MSA")

    fig.add_vline(x=2009, line_width=2, line_dash="dash", line_color="orange",
                  annotation_text="2009 Federal Tax")

    fig.add_vline(x=2019, line_width=2, line_dash="dash", line_color="purple",
                  annotation_text="2019 Tobacco 21")

    # Changepoints
    for idx in cp_idx:
        cp_year = int(national.iloc[idx]["Year"])
        fig.add_vline(
            x=cp_year,
            line_dash="dot",
            line_color="green",
            annotation_text=f"CP: {cp_year}"
        )

    fig.update_layout(
        template="plotly_white",
        title="National Cigarette Consumption Trend with LOESS Smoothing",
        xaxis_title="Year",
        yaxis_title="Packs Per Capita",
        height=550
    )

    return fig

# ---- RUN on port 8061 ----
app2.run_server(host="0.0.0.0", port=8061)



import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from dash import Dash, dcc, html, Input, Output
import json, urllib.request

# --------------------------
# Load dataset
# --------------------------
df = pd.read_csv("/content/Cigarette Consumption(in).csv")
df["state"] = df["state"].str.upper()

years = sorted(df["Year"].unique())
states = sorted(df["state"].unique())

# Region mapping for sunburst
region_map = {
    "WA":"West","OR":"West","CA":"West","NV":"West","ID":"West","MT":"West",
    "WY":"West","UT":"West","CO":"West","AZ":"West","NM":"West","AK":"West","HI":"West",
    "ND":"Midwest","SD":"Midwest","NE":"Midwest","KS":"Midwest","MN":"Midwest",
    "IA":"Midwest","MO":"Midwest","WI":"Midwest","IL":"Midwest","IN":"Midwest","MI":"Midwest","OH":"Midwest",
    "OK":"South","TX":"South","AR":"South","LA":"South","KY":"South","TN":"South",
    "MS":"South","AL":"South","GA":"South","FL":"South","SC":"South","NC":"South",
    "VA":"South","WV":"South","MD":"South","DE":"South",
    "PA":"Northeast","NY":"Northeast","NJ":"Northeast","CT":"Northeast","RI":"Northeast",
    "MA":"Northeast","VT":"Northeast","NH":"Northeast","ME":"Northeast",
    "DC":"Northeast"
}
df["Region"] = df["state"].map(region_map).fillna("Other")

# USA GeoJSON
url = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
with urllib.request.urlopen(url) as response:
    states_geo = json.loads(response.read())

# --------------------------
# Dash App
# --------------------------
app = Dash(__name__)

app.layout = html.Div([

    # HEADER
    html.Div([
        html.H1("Daily Smoking Patterns – Interactive Dashboard",
                style={"textAlign":"center", "color":"white",
                       "background":"linear-gradient(90deg,#1e1e2f,#212140,#1e1e2f)",
                       "padding":"18px", "borderRadius":"8px"}),
        html.H4("By Hiral Choksi",
                style={"textAlign":"center", "color":"#9efcff", "marginTop":"-10px"})
    ]),

    # TOP TABS
    html.Div([
        html.Div("Worldwide", className="tab active-tab"),
        html.Div("Country", className="tab"),
        html.Div("Data", className="tab"),
    ], className="top-bar"),

    html.H2("Exploring Tobacco Consumption Across US States",
            style={"textAlign":"center","color":"#9efcff"}),

    # Main panels
    html.Div([

        # LEFT — USA Map
        html.Div([
            dcc.Graph(id="usa_map", style={"height":"430px"}),
            html.Div(id="caption",
                     style={"textAlign":"center","fontSize":"14px","color":"white"})
        ], style={"width":"60%", "display":"inline-block"}),

        # RIGHT — Sunburst
        html.Div([
            dcc.Graph(id="sunburst_chart", style={"height":"430px"})
        ], style={"width":"38%", "display":"inline-block","marginLeft":"2%"})
    ]),

    # Timeseries Below
    html.Div([
        dcc.Graph(id="timeseries_all", style={"height":"300px"})
    ], style={"width":"96%","margin":"0 auto"}),

    # Slider Section
    html.Div([
        html.Span("Select Year:", style={"marginRight":"10px","color":"white"}),
        dcc.Slider(
            id="year_slider",
            min=min(years),
            max=max(years),
            step=None,
            value=max(years),
            marks={int(y): f"{int(y)}" for y in years[::5]},
            tooltip={"placement":"bottom"}
        )
    ], className="bottom-controls")
])

# --------------------------
# Callback: MAP
# --------------------------
@app.callback(
    Output("usa_map", "figure"),
    Output("caption", "children"),
    Input("year_slider", "value")
)
def update_map(year):
    dff = df[df["Year"] == year]

    fig = px.choropleth(
        dff,
        locations="state",
        locationmode="USA-states",
        color="Y",
        scope="usa",
        color_continuous_scale="Viridis",
        hover_name="state",
        hover_data={"Y":":.2f"},
        labels={"Y":"Cigarette Consumption"},
        title=f"US Cigarette Consumption in {year}"
    )

    fig.update_layout(
        template="plotly_dark",
        margin=dict(l=10,r=10,t=40,b=20),
        geo=dict(bgcolor="rgba(0,0,0,0)")
    )
    fig.update_traces(marker_line_color="white", marker_line_width=0.3)

    return fig, f"Total smoking levels shown for {year}"

# --------------------------
# Callback: Sunburst
# --------------------------
@app.callback(
    Output("sunburst_chart", "figure"),
    Input("year_slider", "value")
)
def update_sunburst(year):
    dff = df[df["Year"] == year]
    sun = dff.groupby(["Region","state"], as_index=False)["Y"].mean()

    fig = px.sunburst(
        sun,
        path=["Region","state"],
        values="Y",
        color="Region",
        color_discrete_sequence=px.colors.qualitative.Set3,
        title=f"Consumption by Region → State ({year})"
    )

    fig.update_layout(template="plotly_dark", margin=dict(l=0,r=0,t=40,b=0))
    return fig

# --------------------------
# Callback: All-State Timeseries
# --------------------------
@app.callback(
    Output("timeseries_all", "figure"),
    Input("year_slider", "value")
)
def update_timeseries(year):
    fig = go.Figure()

    # Individual state lines (light)
    for st in states:
        temp = df[df["state"] == st]
        fig.add_trace(go.Scatter(
            x=temp["Year"],
            y=temp["Y"],
            mode="lines",
            line=dict(width=1, color="rgba(150,150,255,0.12)"),
            hoverinfo="skip",
            showlegend=False
        ))

    # National mean (bold)
    avg = df.groupby("Year", as_index=False)["Y"].mean()
    fig.add_trace(go.Scatter(
        x=avg["Year"],
        y=avg["Y"],
        mode="lines+markers",
        line=dict(width=4, color="#00d4ff"),
        marker=dict(color="#00d4ff"),
        name="National Average"
    ))

    fig.update_layout(
        template="plotly_dark",
        title="Cigarette Consumption Trend (All States)",
        xaxis_title="Year",
        yaxis_title="Consumption per Capita",
        margin=dict(l=40,r=20,t=40,b=40)
    )

    return fig

# --------------------------
# ADVANCED DARK CSS
# --------------------------
app.index_string = """
<!DOCTYPE html>
<html>
<head>
    {%metas%}
    <title>Advanced Tobacco Dashboard</title>
    {%favicon%}
    {%css%}
    <style>
    body {
        font-family: "Inter", "Helvetica Neue", Arial;
        margin:0;
        background:#0e0e1a;
    }
    .top-bar {
        background:#1f1f2e;
        padding:6px 20px;
        display:flex;
        border-bottom:2px solid #00e1ff;
    }
    .tab {
        padding:6px 18px;
        margin-right:6px;
        background:#2b2b3d;
        color:white;
        border-radius:6px;
        cursor:pointer;
        transition:0.3s;
    }
    .tab:hover {
        background:#00e1ff;
        color:black;
    }
    .active-tab {
        background:#00e1ff;
        color:black;
        font-weight:bold;
    }
    .bottom-controls {
        background:#1a1a27;
        padding:14px 20px;
        border-radius:10px;
        margin-top:10px;
        color:white;
    }
    </style>
</head>
<body>
    {%app_entry%}
    <footer>
        {%config%}
        {%scripts%}
        {%renderer%}
    </footer>
</body>
</html>
"""

# --------------------------
# Run server
# --------------------------
app.run_server(host="0.0.0.0", port=8060)

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from dash import Dash, dcc, html, Input, Output
import ruptures as rpt
from statsmodels.nonparametric.smoothers_lowess import lowess
import json, urllib.request

# ============================================================
# LOAD DATA
# ============================================================
df = pd.read_csv("/content/Cigarette Consumption(in).csv")
df["state"] = df["state"].str.upper()
df = df[df["Year"].between(1990, 2019)]

# Engineering tax share
df["state_tax_pct"] = df["State Tax as percentage of Retail Price"] / 100
df["federal_tax_pct"] = df["Federal Tax as percentage of Retail Price"] / 100
df["total_tax_pct"] = df["state_tax_pct"] + df["federal_tax_pct"]

# Region mapping
region_map = {
    "WA":"West","OR":"West","CA":"West","NV":"West","ID":"West","MT":"West",
    "WY":"West","UT":"West","CO":"West","AZ":"West","NM":"West","AK":"West","HI":"West",
    "ND":"Midwest","SD":"Midwest","NE":"Midwest","KS":"Midwest","MN":"Midwest",
    "IA":"Midwest","MO":"Midwest","WI":"Midwest","IL":"Midwest","IN":"Midwest","MI":"Midwest","OH":"Midwest",
    "OK":"South","TX":"South","AR":"South","LA":"South","KY":"South","TN":"South",
    "MS":"South","AL":"South","GA":"South","FL":"South","SC":"South","NC":"South",
    "VA":"South","WV":"South","MD":"South","DE":"South",
    "PA":"Northeast","NY":"Northeast","NJ":"Northeast","CT":"Northeast","RI":"Northeast",
    "MA":"Northeast","VT":"Northeast","NH":"Northeast","ME":"Northeast",
    "DC":"Northeast"
}
df["Region"] = df["state"].map(region_map).fillna("Other")

years = sorted(df["Year"].unique())
states = sorted(df["state"].unique())

# ============================================================
# LOESS + CHANGEPOINT
# ============================================================
def loess_smooth(x, y, frac=0.25):
    sm = lowess(y, x, frac=frac)
    return sm[:,0], sm[:,1]

def changepoints(series, n=3):
    model = rpt.Binseg(model="rbf").fit(series)
    pts = model.predict(n_bkps=n)
    return pts[:-1]

national = df.groupby("Year", as_index=False)["Y"].mean()
cp_idx = changepoints(national["Y"].values, n=3)

# ============================================================
# K-MEANS CLUSTERING
# ============================================================
from sklearn.cluster import KMeans

cluster_data = df.groupby("state").agg({
    "state_tax_pct":"mean",
    "Y":"mean"
}).reset_index()

kmeans = KMeans(n_clusters=4, random_state=42)
cluster_data["cluster"] = kmeans.fit_predict(cluster_data[["state_tax_pct","Y"]])

df = df.merge(cluster_data[["state","cluster"]], on="state")

cluster_colors = {
    0:"#ff6b6b",
    1:"#ffa502",
    2:"#1e90ff",
    3:"#2ed573"
}

# ============================================================
# CORRELATION MATRIX
# ============================================================
corr_cols = ["Y","X1","X2","X3","X4","state_tax_pct","federal_tax_pct","total_tax_pct",
             "Avg Cost Per Pack","Gross Cigarette Tax Revenue"]
corr = df[corr_cols].corr()

# ============================================================
# GEOJSON FOR MAP
# ============================================================
url = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
with urllib.request.urlopen(url) as response:
    us_map = json.loads(response.read())

# ============================================================
# DASH APP
# ============================================================
app = Dash(__name__)

app.layout = html.Div([
    html.H1("Tobacco Tax & Cigarette Consumption (1990–2019)",
            style={"text-align":"center","margin-bottom":"20px"}),

    dcc.Tabs(id="tabs", value="tab1", children=[
        dcc.Tab(label="Overview", value="tab1"),
        dcc.Tab(label="State Clusters", value="tab2"),
        dcc.Tab(label="Correlation", value="tab3"),
        dcc.Tab(label="Geographic Maps", value="tab4"),
        dcc.Tab(label="Elasticity", value="tab5"),
        dcc.Tab(label="Compare States", value="tab6"),
        dcc.Tab(label="Data Table", value="tab7"),
    ]),

    html.Div(id="tab_content", style={"padding":"20px"})
])

# ============================================================
# CALLBACKS
# ============================================================
@app.callback(
    Output("tab_content","children"),
    Input("tabs","value")
)
def render_tab(tab):

    # ------------------ TAB 1: OVERVIEW ------------------
    if tab == "tab1":
        smooth_x, smooth_y = loess_smooth(national["Year"], national["Y"], frac=0.25)

        fig = go.Figure()

        fig.add_trace(go.Scatter(
            x=national["Year"], y=national["Y"],
            mode="lines+markers",
            name="Actual",
            line=dict(color="#6daffe")
        ))

        fig.add_trace(go.Scatter(
            x=smooth_x, y=smooth_y,
            mode="lines",
            name="LOESS Trend",
            line=dict(color="#0047ab", width=4)
        ))

        # policy lines
        fig.add_vline(x=1998, line_color="red", line_dash="dash")
        fig.add_vline(x=2009, line_color="orange", line_dash="dash")
        fig.add_vline(x=2019, line_color="purple", line_dash="dash")

        # changepoints
        for i in cp_idx:
            yr = int(national.iloc[i]["Year"])
            fig.add_vline(x=yr, line_dash="dot", line_color="green")

        fig.update_layout(title="National Trend (LOESS + Policy Events + Change-Points)",
                          template="plotly_white")

        return dcc.Graph(figure=fig)

    # ------------------ TAB 2: CLUSTERS ------------------
    if tab == "tab2":

        fig = px.scatter(cluster_data,
                         x="state_tax_pct", y="Y",
                         color="cluster",
                         color_discrete_map=cluster_colors,
                         hover_name="state",
                         title="K-Means State Clusters")

        return dcc.Graph(figure=fig)

    # ------------------ TAB 3: CORRELATION ------------------
    if tab == "tab3":

        fig = px.imshow(corr, text_auto=True,
                        color_continuous_scale="RdBu_r",
                        title="Correlation Heatmap")

        return dcc.Graph(figure=fig)

    # ------------------ TAB 4: MAPS ------------------
    if tab == "tab4":

        fig = px.choropleth(df,
                            locations="state",
                            locationmode="USA-states",
                            color="state_tax_pct",
                            animation_frame="Year",
                            scope="usa",
                            color_continuous_scale="Reds",
                            title="Animated US Map: Tax Burden")

        return dcc.Graph(figure=fig)

    # ------------------ TAB 5: ELASTICITY ------------------
    if tab == "tab5":

        df_el = df.copy()
        df_el["tax_bin"] = pd.cut(df_el["state_tax_pct"], bins=20)
        g = df_el.groupby("tax_bin", as_index=False).agg(
            tax_pct=("state_tax_pct","mean"),
            cons=("Y","mean")
        )

        # regression
        slope, intercept = np.polyfit(g["tax_pct"], g["cons"], 1)
        line = slope*g["tax_pct"] + intercept

        fig = go.Figure()
        fig.add_trace(go.Scatter(x=g["tax_pct"], y=g["cons"],
                                 mode="markers",
                                 name="Data"))
        fig.add_trace(go.Scatter(x=g["tax_pct"], y=line,
                                 mode="lines",
                                 name="Trend",
                                 line=dict(color="red")))
        fig.update_layout(title="Tax Elasticity Curve",
                          xaxis_title="Tax Share",
                          yaxis_title="Consumption")
        return dcc.Graph(figure=fig)

    # ------------------ TAB 6: COMPARE STATES ------------------
    if tab == "tab6":

        return html.Div([
            html.Label("Select State 1"),
            dcc.Dropdown(options=states, value="NY", id="s1"),

            html.Label("Select State 2"),
            dcc.Dropdown(options=states, value="KY", id="s2"),

            dcc.Graph(id="compare_graph")
        ])

    # ------------------ TAB 7: DATA TABLE ------------------
    if tab == "tab7":
        return html.Div([
            html.H3("Raw Data"),
            dcc.Graph(
                figure=px.scatter(df, x="Year", y="Y", color="state",
                                  title="Scatter Overview (Debug View)")
            )
        ])

# callback for state comparison
@app.callback(
    Output("compare_graph","figure"),
    Input("s1","value"),
    Input("s2","value")
)
def compare_states(a, b):

    fig = go.Figure()

    d1 = df[df["state"]==a]
    d2 = df[df["state"]==b]

    fig.add_trace(go.Scatter(x=d1["Year"], y=d1["Y"], mode="lines",
                             name=f"{a} Consumption"))
    fig.add_trace(go.Scatter(x=d2["Year"], y=d2["Y"], mode="lines",
                             name=f"{b} Consumption"))

    fig.update_layout(title="State Consumption Comparison (1990–2019)",
                      template="plotly_white")

    return fig

# ============================================================
# RUN SERVER
# ============================================================
app.run_server(host="0.0.0.0", port=8060)

!pip install ruptures

!pip install ruptures statsmodels scikit-learn plotly dash jupyter-dash

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from dash import Dash, dcc, html, Input, Output
import ruptures as rpt
from statsmodels.nonparametric.smoothers_lowess import lowess
import json, urllib.request
from sklearn.cluster import KMeans

# ============================================================
# LOAD DATA
# ============================================================
df = pd.read_csv("/content/Cigarette Consumption(in).csv")
df["state"] = df["state"].str.upper()
df = df[df["Year"].between(1990, 2019)]

# Engineering tax share
df["state_tax_pct"] = df["State Tax as percentage of Retail Price"] / 100
df["federal_tax_pct"] = df["Federal Tax as percentage of Retail Price"] / 100
df["total_tax_pct"] = df["state_tax_pct"] + df["federal_tax_pct"]

# Region mapping
region_map = {
    "WA":"West","OR":"West","CA":"West","NV":"West","ID":"West","MT":"West",
    "WY":"West","UT":"West","CO":"West","AZ":"West","NM":"West","AK":"West","HI":"West",
    "ND":"Midwest","SD":"Midwest","NE":"Midwest","KS":"Midwest","MN":"Midwest",
    "IA":"Midwest","MO":"Midwest","WI":"Midwest","IL":"Midwest","IN":"Midwest","MI":"Midwest","OH":"Midwest",
    "OK":"South","TX":"South","AR":"South","LA":"South","KY":"South","TN":"South",
    "MS":"South","AL":"South","GA":"South","FL":"South","SC":"South","NC":"South",
    "VA":"South","WV":"South","MD":"South","DE":"South",
    "PA":"Northeast","NY":"Northeast","NJ":"Northeast","CT":"Northeast","RI":"Northeast",
    "MA":"Northeast","VT":"Northeast","NH":"Northeast","ME":"Northeast",
    "DC":"Northeast"
}
df["Region"] = df["state"].map(region_map).fillna("Other")

years = sorted(df["Year"].unique())
states = sorted(df["state"].unique())

# ============================================================
# LOESS + CHANGEPOINT
# ============================================================
def loess_smooth(x, y, frac=0.25):
    sm = lowess(y, x, frac=frac)
    return sm[:,0], sm[:,1]

def changepoints(series, n=3):
    model = rpt.Binseg(model="rbf").fit(series)
    pts = model.predict(n_bkps=n)
    return pts[:-1]

national = df.groupby("Year", as_index=False)["Y"].mean()
cp_idx = changepoints(national["Y"].values, n=3)

# ============================================================
# K-MEANS CLUSTERING
# ============================================================
cluster_data = df.groupby("state").agg({
    "state_tax_pct":"mean",
    "Y":"mean"
}).reset_index()

kmeans = KMeans(n_clusters=4, random_state=42)
cluster_data["cluster"] = kmeans.fit_predict(cluster_data[["state_tax_pct","Y"]])

df = df.merge(cluster_data[["state","cluster"]], on="state")

cluster_colors = {
    0:"#00b4ff",
    1:"#ff6bcb",
    2:"#ffae00",
    3:"#2ed573"
}

# ============================================================
# CORRELATION MATRIX
# ============================================================
corr_cols = ["Y","X1","X2","X3","X4",
             "state_tax_pct","federal_tax_pct","total_tax_pct",
             "Avg Cost Per Pack","Gross Cigarette Tax Revenue"]

corr = df[corr_cols].corr()

# ============================================================
# GEOJSON FOR MAP
# ============================================================
url = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
with urllib.request.urlopen(url) as response:
    us_map = json.loads(response.read())

# ============================================================
# DARK MODE STYLING
# ============================================================
dark_bg = "#0e0e10"
card_bg = "#1a1b1f"
text_color = "white"
neon_blue = "#00b4ff"
neon_pink = "#ff4ecd"

tab_style = {
    "backgroundColor": card_bg,
    "color": text_color,
    "padding": "10px",
    "fontWeight": "bold",
    "border": "none"
}
tab_selected = {
    "backgroundColor": neon_blue,
    "color": "black",
    "padding": "10px",
    "fontWeight": "bold",
    "border": "none"
}

# ============================================================
# DASH APP
# ============================================================
app = Dash(__name__)

app.layout = html.Div(
    style={"backgroundColor": dark_bg, "color": text_color, "padding": "10px"},
    children=[
        html.H1(
            "Tobacco Tax & Cigarette Consumption Dashboard (1990–2019)",
            style={"textAlign":"center","color":neon_blue,"fontWeight":"bold"}
        ),
        html.H3(
            "By Hiral Choksi — UConn",
            style={"textAlign":"center","color":neon_pink,"marginBottom":"20px"}
        ),

        dcc.Tabs(
            id="tabs",
            value="tab1",
            children=[
                dcc.Tab(label="Overview", value="tab1", style=tab_style, selected_style=tab_selected),
                dcc.Tab(label="State Clusters", value="tab2", style=tab_style, selected_style=tab_selected),
                dcc.Tab(label="Correlation", value="tab3", style=tab_style, selected_style=tab_selected),
                dcc.Tab(label="Geographic Maps", value="tab4", style=tab_style, selected_style=tab_selected),
                dcc.Tab(label="Elasticity", value="tab5", style=tab_style, selected_style=tab_selected),
                dcc.Tab(label="Compare States", value="tab6", style=tab_style, selected_style=tab_selected),
                dcc.Tab(label="Data Table", value="tab7", style=tab_style, selected_style=tab_selected),
            ],
        ),

        html.Div(id="tab_content", style={"padding":"20px"})
    ]
)

# ============================================================
# TAB RENDERING
# ============================================================
@app.callback(
    Output("tab_content","children"),
    Input("tabs","value")
)
def render_tab(tab):

    # ---------------- TAB 1: OVERVIEW ----------------
    if tab == "tab1":
        smooth_x, smooth_y = loess_smooth(national["Year"], national["Y"])

        fig = go.Figure()

        fig.add_trace(go.Scatter(
            x=national["Year"], y=national["Y"],
            mode="lines+markers",
            name="Actual",
            line=dict(color=neon_blue)
        ))

        fig.add_trace(go.Scatter(
            x=smooth_x, y=smooth_y,
            mode="lines",
            name="LOESS Trend",
            line=dict(color=neon_pink, width=4)
        ))

        # policy markers
        for yr, col in zip([1998,2009,2019], ["red","orange","purple"]):
            fig.add_vline(x=yr, line_color=col, line_dash="dash")

        # change-points
        for i in cp_idx:
            year = int(national.iloc[i]["Year"])
            fig.add_vline(x=year, line_dash="dot", line_color="lime")

        fig.update_layout(
            template="plotly_dark",
            title="National Trend with LOESS + Policy Events + changepoints"
        )

        return dcc.Graph(figure=fig)

    # ---------------- TAB 2: CLUSTERS ----------------
    if tab == "tab2":
        fig = px.scatter(
            cluster_data,
            x="state_tax_pct",
            y="Y",
            color="cluster",
            color_discrete_map=cluster_colors,
            hover_name="state",
            title="K-Means State Clusters : State Clusters based on Tax Share & Consumption"
        )
        fig.update_layout(template="plotly_dark")
        return dcc.Graph(figure=fig)

    # ---------------- TAB 3: CORRELATION ----------------
    if tab == "tab3":
        fig = px.imshow(
            corr,
            text_auto=True,
            color_continuous_scale="RdBu_r",
            title="Correlation Heatmap"
        )
        fig.update_layout(template="plotly_dark")
        return dcc.Graph(figure=fig)

    # ---------------- TAB 4: MAPS ----------------
    if tab == "tab4":
        fig = px.choropleth(
            df,
            locations="state",
            locationmode="USA-states",
            color="state_tax_pct",
            animation_frame="Year",
            scope="usa",
            color_continuous_scale="Turbo",
            title="Animated US Map: State Tax Burden Over Time"
        )
        fig.update_layout(template="plotly_dark")
        return dcc.Graph(figure=fig)

    # ---------------- TAB 5: ELASTICITY ----------------
    if tab == "tab5":
        df_el = df.copy()
        df_el["tax_bin"] = pd.cut(df_el["state_tax_pct"], bins=20)

        g = df_el.groupby("tax_bin", as_index=False).agg(
            x=("state_tax_pct","mean"),
            y=("Y","mean")
        )

        slope, intercept = np.polyfit(g["x"], g["y"], 1)
        line = slope*g["x"] + intercept

        fig = go.Figure()
        fig.add_trace(go.Scatter(x=g["x"], y=g["y"], mode="markers", marker=dict(color=neon_blue), name="Data"))
        fig.add_trace(go.Scatter(x=g["x"], y=line, mode="lines", line=dict(color=neon_pink, width=4), name="Trend"))

        fig.update_layout(template="plotly_dark", title="Elasticity Curve: Tax Share vs Consumption")
        return dcc.Graph(figure=fig)

    # ---------------- TAB 6: COMPARE STATES ----------------
    if tab == "tab6":
        return html.Div([
            html.Label("Select State 1", style={"color":"white"}),
            dcc.Dropdown(options=states, value="NY", id="s1"),

            html.Br(),

            html.Label("Select State 2", style={"color":"white"}),
            dcc.Dropdown(options=states, value="KY", id="s2"),

            html.Br(),

            dcc.Graph(id="compare_graph")
        ])

    # ---------------- TAB 7: DATA TABLE ----------------
    if tab == "tab7":
        return html.Div([
            html.H3("Dataset Overview", style={"color": neon_blue}),
            dcc.Graph(figure=px.scatter(df, x="Year", y="Y", color="state"))
        ])

# ============================================================
# CALLBACK: STATE COMPARISON
# ============================================================
@app.callback(
    Output("compare_graph","figure"),
    Input("s1","value"),
    Input("s2","value")
)
def compare_states(a, b):
    fig = go.Figure()

    d1 = df[df["state"] == a]
    d2 = df[df["state"] == b]

    fig.add_trace(go.Scatter(x=d1["Year"], y=d1["Y"], mode="lines", name=a, line=dict(width=4, color=neon_blue)))
    fig.add_trace(go.Scatter(x=d2["Year"], y=d2["Y"], mode="lines", name=b, line=dict(width=4, color=neon_pink)))

    fig.update_layout(template="plotly_dark", title=f"{a} vs {b} — Consumption Trends (1990–2019)")
    return fig

# ============================================================
# RUN DASH (COLAB)
# ============================================================
app.run_server(host="0.0.0.0", port=8060)

from google.colab.output import eval_js

print("Your Dash URL for port 8060:")
print(eval_js("google.colab.kernel.proxyPort(8060)"))